const projectsData = {
  "VXI": { 
    "mainImage": "images/VXI/4.jpg",
    "projectImage1": "images/VXI/2.jpg",
    "projectImage2": "images/VXI/3.jpg",
    "projectImage3": "images/VXI/1.jpg",
    "client": "VXI", 
    "partners": "Gensler",
    "team": ["Kasey Christensen", "Jazmin Ocegueda", "Jo Tapia", "Sarah Ferneau"],
    "photographer": "Virginie Chopelin Valdois",
    "year": "2024",
    "location": "Los Angeles, CA",
    "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "title": "VXI",
    "type": "Corporate"
  },
  "AmazonCA14": { 
    "mainImage": "images/AmazonCA14/4.jpg",
    "projectImage1": "images/AmazonCA14/2.jpg",
    "projectImage2": "images/AmazonCA14/3.jpg",
    "projectImage3": "images/AmazonCA14/1.jpg",
    "client": "AmazonCA14", 
    "partners": "Gensler",
    "team": ["Kasey Christensen", "Jazmin Ocegueda", "Jo Tapia", "Sarah Ferneau"],
    "photographer": "Virginie Chopelin Valdois",
    "year": "2024",
    "location": "Los Angeles, CA",
    "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "title": "AmazonCA14",
    "type": "Commercial"
  },
  "Skywalk": { 
    "mainImage": "images/Skywalk/4.jpg",
    "projectImage1": "images/Skywalk/2.jpg",
    "projectImage2": "images/Skywalk/3.jpg",
    "projectImage3": "images/Skywalk/1.jpg",
    "client": "Skywalk", 
    "partners": "Gensler",
    "team": ["Kasey Christensen", "Jazmin Ocegueda", "Jo Tapia", "Sarah Ferneau"],
    "photographer": "Virginie Chopelin Valdois",
    "year": "2024",
    "location": "Los Angeles, CA",
    "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "title": "Skywalk",
    "type": "Residential"
  },
  "AmazonRBS": { 
    "mainImage": "images/AmazonRBS/4.jpg",
    "projectImage1": "images/AmazonRBS/2.jpg",
    "projectImage2": "images/AmazonRBS/3.jpg",
    "projectImage3": "images/AmazonRBS/1.jpg",
    "client": "AmazonRBS", 
    "partners": "Gensler",
    "team": ["Kasey Christensen", "Jazmin Ocegueda", "Jo Tapia", "Sarah Ferneau"],
    "photographer": "Virginie Chopelin Valdois",
    "year": "2024",
    "location": "Los Angeles, CA",
    "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "title": "AmazonRBS",
    "type": "Corporate"
  },
  "AlFuttaim": { 
    "mainImage": "images/AlFuttaim/4.jpg",
    "projectImage1": "images/AlFuttaim/2.jpg",
    "projectImage2": "images/AlFuttaim/3.jpg",
    "projectImage3": "images/AlFuttaim/1.jpg",
    "client": "AlFuttaim", 
    "partners": "Gensler",
    "team": ["Kasey Christensen", "Jazmin Ocegueda", "Jo Tapia", "Sarah Ferneau"],
    "photographer": "Virginie Chopelin Valdois",
    "year": "2024",
    "location": "Los Angeles, CA",
    "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "title": "AlFuttaim",
    "type": "Commercial"
  },
  "Deloitte": { 
    "mainImage": "images/Deloitte/4.jpg",
    "projectImage1": "images/Deloitte/2.jpg",
    "projectImage2": "images/Deloitte/3.jpg",
    "projectImage3": "images/Deloitte/1.jpg",
    "client": "Deloitte", 
    "partners": "Gensler",
    "team": ["Kasey Christensen", "Jazmin Ocegueda", "Jo Tapia", "Sarah Ferneau"],
    "photographer": "Virginie Chopelin Valdois",
    "year": "2024",
    "location": "Los Angeles, CA",
    "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "title": "Deloitte",
    "type": "Corporate"
  },
  "Menacom": { 
    "mainImage": "images/Menacom/4.jpg",
    "projectImage1": "images/Menacom/2.jpg",
    "projectImage2": "images/Menacom/3.jpg",
    "projectImage3": "images/Menacom/1.jpg",
    "client": "Menacom", 
    "partners": "Gensler",
    "team": ["Kasey Christensen", "Jazmin Ocegueda", "Jo Tapia", "Sarah Ferneau"],
    "photographer": "Virginie Chopelin Valdois",
    "year": "2024",
    "location": "Los Angeles, CA",
    "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "title": "Menacom",
    "type": "Residential"
  },
  "MSD": { 
    "mainImage": "images/MSD/4.jpg",
    "projectImage1": "images/MSD/2.jpg",
    "projectImage2": "images/MSD/3.jpg",
    "projectImage3": "images/MSD/1.jpg",
    "client": "MSD", 
    "partners": "Gensler",
    "team": ["Kasey Christensen", "Jazmin Ocegueda", "Jo Tapia", "Sarah Ferneau"],
    "photographer": "Virginie Chopelin Valdois",
    "year": "2024",
    "location": "Los Angeles, CA",
    "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "title": "MSD",
    "type": "Commercial"
  },
  "Co55": { 
    "mainImage": "images/Co55/4.jpg",
    "projectImage1": "images/Co55/2.jpg",
    "projectImage2": "images/Co55/3.jpg",
    "projectImage3": "images/Co55/1.jpg",
    "client": "Co55", 
    "partners": "Gensler",
    "team": ["Kasey Christensen", "Jazmin Ocegueda", "Jo Tapia", "Sarah Ferneau"],
    "photographer": "Virginie Chopelin Valdois",
    "year": "2024",
    "location": "Los Angeles, CA",
    "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "title": "Co55",
    "type": "Residential"
  },
  "AE7": { 
    "mainImage": "images/AE7/4.jpg",
    "projectImage1": "images/AE7/2.jpg",
    "projectImage2": "images/AE7/3.jpg",
    "projectImage3": "images/AE7/1.jpg",
    "client": "AE7", 
    "partners": "Gensler",
    "team": ["Kasey Christensen", "Jazmin Ocegueda", "Jo Tapia", "Sarah Ferneau"],
    "photographer": "Virginie Chopelin Valdois",
    "year": "2024",
    "location": "Los Angeles, CA",
    "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "title": "AE7",
    "type": "Commercial"
  },
  "Kredit": { 
    "mainImage": "images/Kredit/4.jpg",
    "projectImage1": "images/Kredit/2.jpg",
    "projectImage2": "images/Kredit/3.jpg",
    "projectImage3": "images/Kredit/1.jpg",
    "client": "Kredit", 
    "partners": "Gensler",
    "team": ["Kasey Christensen", "Jazmin Ocegueda", "Jo Tapia", "Sarah Ferneau"],
    "photographer": "Virginie Chopelin Valdois",
    "year": "2024",
    "location": "Los Angeles, CA",
    "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "title": "Kredit",
    "type": "Corporate"
  },
  "Capital": { 
    "mainImage": "images/Capital/4.jpg",
    "projectImage1": "images/Capital/2.jpg",
    "projectImage2": "images/Capital/3.jpg",
    "projectImage3": "images/Capital/1.jpg",
    "client": "Capital", 
    "partners": "Gensler",
    "team": ["Kasey Christensen", "Jazmin Ocegueda", "Jo Tapia", "Sarah Ferneau"],
    "photographer": "Virginie Chopelin Valdois",
    "year": "2024",
    "location": "Los Angeles, CA",
    "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "title": "Capital",
    "type": "Residential"
  },
  "KCG": { 
    "mainImage": "images/KCG/4.jpg",
    "projectImage1": "images/KCG/2.jpg",
    "projectImage2": "images/KCG/3.jpg",
    "projectImage3": "images/KCG/1.jpg",
    "client": "KCG", 
    "partners": "Gensler",
    "team": ["Kasey Christensen", "Jazmin Ocegueda", "Jo Tapia", "Sarah Ferneau"],
    "photographer": "Virginie Chopelin Valdois",
    "year": "2024",
    "location": "Los Angeles, CA",
    "overview": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "title": "KCG",
    "type": "Corporate"
  }
};
